services:
  - type: web
    name: personal-finance-manager
    env: docker
    dockerfilePath: Dockerfile
    plan: free
    healthCheckPath: /api/health
    envVars:
      - key: COOKIE_SECURE
        value: "true"
      - key: APP_TIMEZONE
        value: "Asia/Kolkata"
      - key: DB_URL
        sync: false
      - key: DB_USER
        sync: false
      - key: DB_PASSWORD
        sync: false
